on:
  push:
    branches:
      - master
  pull_request:


permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: cd web && bun install --frozen-lockfile
      - name: Lint
        run: cd web && bun run lint
      - name: Typecheck
        run: cd web && bun run typecheck
